{{- include "anvilkit-agent-inference.require" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anvilkit-agent-inference.fullname" . }}
  labels:
    {{- include "anvilkit-agent-inference.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml (merge (dict "tls" (dict "mode" .Values.tls.mode) "development" (dict "enabled" .Values.development.enabled)) (deepCopy .Values.config)) | nindent 4 }}
